Homework2
================

## Library

``` r
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.2.1     ✔ readr     2.2.0
    ## ✔ forcats   1.0.1     ✔ stringr   1.6.0
    ## ✔ ggplot2   4.0.3     ✔ tibble    3.3.1
    ## ✔ lubridate 1.9.5     ✔ tidyr     1.3.2
    ## ✔ purrr     1.2.2     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

``` r
library(readxl)
```

## Problem 1

``` r
NY_transit_df =
  read.csv(
    "data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv",
    na = c("",".","NA")
  ) |>
  janitor::clean_names() |>
  select(line, station_name, station_latitude, station_longitude,
         route1:route11, entry, vending, entrance_type,ada
  ) |>
  mutate(entry = case_match(
    entry,
    "YES" ~ TRUE,
    "NO" ~ FALSE))
```

    ## Warning: There was 1 warning in `mutate()`.
    ## ℹ In argument: `entry = case_match(entry, "YES" ~ TRUE, "NO" ~ FALSE)`.
    ## Caused by warning:
    ## ! `case_match()` was deprecated in dplyr 1.2.0.
    ## ℹ Please use `recode_values()` instead.

### Write a short paragraph about this dataset

This dataset contains information about subway entrances and exits in
NYC. The variables include line, station name, station latitude and
longitude, routes served, entry, vending, entrance type, and ADA
compliance. I cleaned the column names, kept the required variables, and
changed `entry` from YES/NO to TRUE/FALSE. The cleaned dataset has 1868
rows and 19 columns. These data are not fully tidy because route names
are stored in separate columns, from `route1` to `route11`.

### Answer the following questions using these data

``` r
station_count =
  NY_transit_df |>
  distinct(line, station_name) |>
  nrow()

station_count
```

    ## [1] 465

There are r station_count distinct stations, identified by line and
station name.

``` r
ada_station_count =
  NY_transit_df |>
  filter(ada == TRUE) |>
  distinct(line, station_name) |>
  nrow()

ada_station_count
```

    ## [1] 84

There are r ada_station_count ADA-compliant stations.

``` r
no_vending_summary =
  NY_transit_df |>
  filter(vending == "NO") |>
  summarise(
    total = n(),
    allow_entry = sum(entry),
    proportion = mean(entry)
  )

no_vending_summary
```

    ##   total allow_entry proportion
    ## 1   183          69  0.3770492

Among entrances and exits without vending, r
round(no_vending_summary\$proportion \* 100, 2)% allow entry.

### Reformat data and answer

``` r
NY_transit_tidy_df =
  NY_transit_df |>
  mutate(
    across(route1:route11, as.character)
  ) |>
  pivot_longer(
    cols = route1:route11,
    names_to = "route_number",
    names_prefix = "route",
    values_to = "route_name",
    values_drop_na = TRUE
  ) |>
  mutate(
    route_number = as.integer(route_number)
  )
```

``` r
a_station_count =
  NY_transit_tidy_df |>
  filter(route_name == "A") |>
  distinct(line, station_name) |>
  nrow()

a_station_count
```

    ## [1] 60

After reshaping the route columns into route_number and route_name,
there are r a_station_count distinct stations that serve the A train.

``` r
a_ada_station_count =
  NY_transit_tidy_df |>
  filter(
    route_name == "A",
    ada == TRUE
  ) |>
  distinct(line, station_name) |>
  nrow()

a_ada_station_count
```

    ## [1] 17

Of the stations that serve the A train, r a_ada_station_count are ADA
compliant.

## Problem 2

### Clean Mr. Trash Wheel

``` r
mr_trash_df =
  read_excel(
    "data/202610 Trash Wheel Collection Data.xlsx",
    sheet = "Mr. Trash Wheel", range = "A2:N742"
  ) |>
  janitor::clean_names() |>
  filter(!is.na(dumpster)) |>
  mutate(
    sports_balls = as.integer(round(sports_balls)),
    month = str_trim(month),
    year = as.integer(year),
    trash_wheel = "Mr. Trash Wheel"
  )
```

### Clean Professor Trash Wheel

``` r
professor_trash_df =
  read_excel(
    "data/202610 Trash Wheel Collection Data.xlsx",
    sheet = "Professor Trash Wheel",
    range = "A2:M139"
  ) |>
  janitor::clean_names() |>
  filter(!is.na(dumpster)) |>
  mutate(
    plastic_bottles = as.numeric(
      na_if(plastic_bottles, "dive")),
    month = str_trim(month),
    year = as.integer(year),
    trash_wheel = "Professor Trash Wheel"
  )
```

### Clean Gwynnda

``` r
gwynnda_trash_df =
  read_excel(
    "data/202610 Trash Wheel Collection Data.xlsx",
    sheet = "Gwynnda the Good Wheel of the W",
    range = "A2:L394"
  ) |>
  janitor::clean_names() |>
  filter(!is.na(dumpster)) |>
  mutate(
    month = str_trim(month),
    year = as.integer(year),
    trash_wheel = "Gwynnda"
  )
```

### Combine these datasets

``` r
trash_wheel_df =
  bind_rows(
    mr_trash_df,
    professor_trash_df,
    gwynnda_trash_df
  )
```

``` r
professor_total_weight =
  trash_wheel_df |>
  filter(trash_wheel == "Professor Trash Wheel") |>
  pull(weight_tons) |>
  sum()
professor_total_weight
```

    ## [1] 294.96

``` r
gwynnda_june_cigarettes =
  trash_wheel_df |>
  filter(
    trash_wheel == "Gwynnda",
    year == 2022,
    month == "June"
  ) |>
  pull(cigarette_butts) |>
  sum()
gwynnda_june_cigarettes
```

    ## [1] 18120

The combined dataset contains 1269 observations from Mr. Trash Wheel,
Professor Trash Wheel, and Gwynnda. Each observation is a dumpster
record. Key variables include the date, weight in tons, volume in cubic
yards, and counts of items such as plastic bottles and cigarette butts.
The `trash_wheel` variable shows which wheel each record comes from.
Some variables are not available for all three wheels and are recorded
as `NA`. For the available data, Professor Trash Wheel collected a total
of 294.96 tons of trash. Gwynnda collected 1.812^{4} cigarette butts in
June 2022.

## Problem 3

``` r
baseline_raw_df =
  read_csv(
    "data_mci/MCI_baseline.csv",
    skip = 1,
    na = c("", ".", "NA")
  ) |>
  janitor::clean_names()
```

    ## Rows: 483 Columns: 6
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (6): ID, Current Age, Sex, Education, apoe4, Age at onset
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
baseline_df =
  baseline_raw_df |>
  rename(
    baseline_age = current_age,
    mci_onset_age = age_at_onset
  ) |>
  mutate(
    sex = factor(
      sex,
      levels = c(0, 1),
      labels = c("Female", "Male")),
    apoe4 = factor(
      apoe4,
      levels = c(0, 1),
      labels = c("Non-carrier", "Carrier"))
  ) |>
  filter(
    is.na(mci_onset_age) | mci_onset_age > baseline_age)

glimpse(baseline_df)
```

    ## Rows: 479
    ## Columns: 6
    ## $ id            <dbl> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 1…
    ## $ baseline_age  <dbl> 63.1, 65.6, 62.5, 69.8, 66.0, 62.5, 66.5, 67.2, 66.7, 64…
    ## $ sex           <fct> Female, Female, Male, Female, Male, Male, Male, Female, …
    ## $ education     <dbl> 16, 20, 16, 16, 16, 16, 18, 18, 16, 18, 16, 18, 12, 20, …
    ## $ apoe4         <fct> Carrier, Carrier, Carrier, Non-carrier, Non-carrier, Non…
    ## $ mci_onset_age <dbl> NA, NA, 66.8, NA, 68.7, NA, 74.0, NA, NA, NA, NA, NA, 69…

``` r
recruited_count = nrow(baseline_raw_df)

eligible_count = nrow(baseline_df)

excluded_count = recruited_count - eligible_count

mci_count =
  baseline_df |>
  summarise(
    total = sum(!is.na(mci_onset_age))
  ) |>
  pull(total)

average_baseline_age =
  baseline_df |>
  pull(baseline_age) |>
  mean()

women_carrier_proportion =
  baseline_df |>
  filter(sex == "Female") |>
  summarise(
    proportion = mean(apoe4 == "Carrier")
  ) |>
  pull(proportion)
```

The baseline dataset contains participants’ ID, baseline age, sex,
education, APOE4 carrier status, and age at MCI onset. I skipped the
first row because it contains variable descriptions and treated “.” as a
missing value. I renamed the age variables and converted sex and APOE4
status to factors. I removed participants whose MCI onset age was less
than or equal to their baseline age. Participants with missing onset age
were retained because they remained MCI-free during follow-up.

The original dataset contains 483 participants. After excluding 4
participants, 479 remain, with one row per participant. Of these, 93
developed MCI during follow-up. The average baseline age is 65.03 years.
Among women, 30% are APOE4 carriers.
